// Generated by CoffeeScript 1.10.0
(function() {
  var random, randoms;

  random = function(amount, excludes, cb) {
    var i, len, num, rand, rands;
    rands = [];
    while (amount > 0) {
      amount--;
      rand = Math.floor(Math.random() * (excludes[1] - excludes[0]));
      for (i = 0, len = rands.length; i < len; i++) {
        num = rands[i];
        if (num === rand) {
          continue;
        }
      }
      rands.push(rand);
    }
    return cb(rands);
  };

  randoms = random(5, [5, 10], function(result) {
    return console.log(result);
  });

}).call(this);
